Traceback (most recent call last):
  File "/home/jon/.conda/envs/fbase/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/jon/.conda/envs/fbase/lib/python3.12/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jon/.conda/envs/fbase/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jon/.conda/envs/fbase/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/jon/.conda/envs/fbase/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/jon/.conda/envs/fbase/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/jon/.conda/envs/fbase/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
temperatures = [200, 220, 240, 260, 280, 300, 320, 340, 360, 380, 400]

temperatures ** 2
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[2], line 3[0m
[1;32m      1[0m temperatures [38;5;241m=[39m [[38;5;241m200[39m, [38;5;241m220[39m, [38;5;241m240[39m, [38;5;241m260[39m, [38;5;241m280[39m, [38;5;241m300[39m, [38;5;241m320[39m, [38;5;241m340[39m, [38;5;241m360[39m, [38;5;241m380[39m, [38;5;241m400[39m]
[0;32m----> 3[0m [43mtemperatures[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43m [49m[38;5;241;43m2[39;49m

[0;31mTypeError[0m: unsupported operand type(s) for ** or pow(): 'list' and 'int'

